baseURL = "https://onurustunel.github.io/"
languageCode = "en-us"
title = "Onur Ustunel"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
author = "Onur Ustunel"
description = "Notes on Swift and SwiftUI. Also talking about architecture and performance."
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true

[params.homeInfoParams]
Title = "Onur Ustunel"
Content = "Notes on Swift and SwiftUI. Also talking about architecture and performance."

[[params.socialIcons]]
name = "github"
url = "https://github.com/onurustunel"